### ISSUE TITLE
Update "killed" the admin_overrides system

### ISSUE THREAD

**Issue by Dying-Ducks** [schwarper/cs2-admin#11]
I use the admin_overrides.json from counterstrikesharp to disable the admin requirement for css_map on my server and it worked flawlessly.

The other day I tried to update my cs2-admin from 0.0.6 to 0.0.9 and the newest version will no longer execute the change map command. 

The plugin recognize the admin_overrides.json as it doesn’t reply with a "permission missing" error.
Also, it listens to the command as it searches for the maps as it will generate the "map not found" error message, if you request a non-existing map.
But if you request a known map, it just does nothing. No error, no map change. Just nothing.

With "css_rcon css_map" I still can change the map, so the command works in general, but not using css_rcon was the whole point in the first place.

I tried to look up what changed between the versions but couldn’t find anything besides the new config’s names. Naturally I made sure to use the new names in the config file.
I really don’t know that could cause this bug.

**Comment by Dying-Ducks** [comment]
I did some further testing and can confirm that the issue was introduces with release 0.0.8 as this version shows exactly the same behavior as 0.0.9.

So somewhere between 0.0.6 and 0.0.8 it went wrong.

**Comment by schwarper** [comment]
@Dying-Ducks 

Does this problem still exist in the new version?

**Comment by schwarper** [comment]
Timeout
