### ISSUE TITLE
Tag color not working in 1.1

### ISSUE THREAD

**Issue by M-archand** [schwarper/cs2-admin#16]
I'm not using any other plugins that manipulate chat or colors.

![image](https://github.com/user-attachments/assets/554755b3-fe07-4540-b5c0-fdb09cbfdd9e)

![image](https://github.com/user-attachments/assets/62182fb1-1151-499e-bd41-d601c500ba7b)

**Comment by schwarper** [comment]
> I'm not using any other plugins that manipulate chat or colors.
> 
> ![image](https://private-user-images.githubusercontent.com/13469995/363027967-554755b3-fe07-4540-b5c0-fdb09cbfdd9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTA2NjQsIm5iZiI6MTcyNDk5MDM2NCwicGF0aCI6Ii8xMzQ2OTk5NS8zNjMwMjc5NjctNTU0NzU1YjMtZmUwNy00NTQwLWI1YzAtZmRiMDljYmZkZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAzNTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NjhhNjJhNTc3ZDAyZGY2Y2JkOTIzZTkxY2I4NDE4NzM1MzcwYjE1ODBmMmJlZjRkNWJhZjU3ZDZiMjJlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VqyT79M02ApUToOCoCkLoTmR3qpWIIv-qpjfort0n8)
> 
> ![image](https://private-user-images.githubusercontent.com/13469995/363027887-62182fb1-1151-499e-bd41-d601c500ba7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTA2NjQsIm5iZiI6MTcyNDk5MDM2NCwicGF0aCI6Ii8xMzQ2OTk5NS8zNjMwMjc4ODctNjIxODJmYjEtMTE1MS00OTllLWJkNDEtZDYwMWM1MDBiYTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAzNTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZWQwMTY1OGY0ZDg3ZjNlNzI1MzQ4YmE3NWI1MDE4ODM3NWRkOGJiMzI4MWJjNWU1ZTI3MGUyZmI3MTBhOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SuRRokyKXAETXCfLtChctj2DYwA5NAq-8AqL7du-QMU)

This message was sent by CounterStrikeSharp. Text will appear in colour as if someone slays someone.
