### ISSUE TITLE
[REQ] Support for admin and everyone messages using @

### ISSUE THREAD

**Issue by crashzk** [schwarper/cs2-admin#19]
SourceMod had a feature where players with admin used @ no say and sent messages to everyone as ADMIN.

And if you sent it to say_team and sent a private message to all admins only, would something like that be possible?

**Comment by schwarper** [comment]
@crashzk 
it will be added in next release, thanks.

**Comment by schwarper** [comment]
https://github.com/schwarper/cs2-admin/commit/8a521c9dd6027631976fa728e8fa14cac7bbf1c3
