### ISSUE TITLE
[REQ] Improvements to Admin Commands

### ISSUE THREAD

**Issue by crashzk** [schwarper/cs2-admin#2]
Could you expect some command to update an admin that has already been added to the database?

-  `css_updateadmin `

Another question would be how does the command work?
- `css_addadmin <steamid> <group> <immunity>`

Group and immunity would be the ones we create in CSSharp correct? Can we expect flag support too?
- `css_addadmin <steamid> <group/flags> <immunity>`
Or
- `css_addadmin <steamid> <flags> <group> <immunity>`

Relation to admin time added, do you want to add it too?
- `css_addadmin <steamid> <group> <immunity> <X minutes>`

**Comment by schwarper** [comment]
css_addadmin addes admin to admins.json not database. Flags will be added in another update. About temporary admin, i'm not sure that cssharp allows it via admins.json.
