### ISSUE TITLE
[REQ] Support for adding/removing/updating admins

### ISSUE THREAD

**Issue by crashzk** [schwarper/cs2-admin#21]
Any command to add/remove admins? So how to update those already added?

Previous versions already had it from what I remember. Or how would the admin system work now, all manually in the CSSharp **`admins.json`** file?

**Comment by schwarper** [comment]
@crashzk 
I will add css_addadmin and css_removeadmin commands when I have time.

**Comment by schwarper** [comment]
https://github.com/schwarper/cs2-admin/commit/76ae0699267c9a9e71c770a98403b12ac6f89ba0
